services:
  redmine:
    container_name: ${PROJECT_NAME}-apache
    hostname: ${PROJECT_NAME}-apache
    image: a22antoniofu/apache
    ports:
      - "80:80"
    environment:
      REDMINE_DB_MYSQL: ${PROJECT_NAME}-db
      REDMINE_DB_USERNAME: ${MYSQL_USER}
      REDMINE_DB_PASSWORD: ${MYSQL_PASSWORD}
      REDMINE_SECRET_KEY_BASE: supersecretkey
      TZ: ${TZ}
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: ${PROJECT_NAME}-db
    hostname: ${PROJECT_NAME}-db
    image: ${IMAGE_DB}:${IMAGE_VERSION_DB}
    ports:
      - "${PORT_OUT_DB}:${PORT_IN_DB}"
    volumes:
      - ${VOLUME_DB}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: password
      TZ: ${TZ}
    restart: unless-stopped
